### ISSUE TITLE
My wife left me

### ISSUE THREAD

**Issue by lufinkey** [bhoeting/search-engine#1]
Um yes I tried using your so called "search" engine to find my wife that left me 15 years ago for a half horse, half centaur man, but so far it hasn't been helpful AT ALL. I'd like to speak to the manager of this repository because I believe I am entitled to a full refund and a new wife thank you

**Comment by bhoeting** [comment]
I'm very sorry sir.  We've had complaints strangely similar to this before and we're working on resolving the issue as quickly as possible.  Unfortunately, we cannot offer you a refund because you didn't pay anything, nor can we guarantee any new wife we provide won't also leave you.  We do wish you good luck and hope that you find love one day.
